apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix:

resources:
- appdeploy.yaml
- appingress.yaml
- secret.yaml
- rmqservice.yaml
- rmqdeploy.yaml
- mcservice.yaml
- mcdep.yaml
- dbservice.yaml
- dbdeploy.yaml
- dbpvc.yaml
- appservice.yaml
