apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/mathiasejoh/argocd-example-install.git
    path: charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true


